services:
  - type: web
    name: nexops
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan storage:link || true
    startCommand: php -S 0.0.0.0:$PORT -t public